name: enough_platform_widgets
description: Useful platform aware widgets to bring a Material app to Cupertino.
version: 0.8.0
homepage: https://github.com/Enough-Software/enough_platform_widgets

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  cupertino_stepper: ^0.2.1
  cupertino_progress_bar: ^0.2.0
  flutter:
    sdk: flutter
  flutter_platform_widgets: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
