# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      # The flutter action needs java so include it
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
    # Include the flutter action
      - uses: dart-lang/setup-dart@1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'  

      - name: Install dependencies
        run: flutter doctor
        run: flutter pub get

      # Uncomment this step to verify the use of 'dart format' on each commit.
      # - name: Verify formatting
      #   run: dart format --output=none --set-exit-if-changed .

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        run: dart analyze
